spring.application.name=demo-producto-pedido-service
server.port=8080
# Configuracion JDBC MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_electrostore
spring.datasource.username=root
spring.datasource.password=AD777o
# Configuracion Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
